spring:
  application:
    name: authsvr
  profiles:
    active: dev
  #jackson\u5E8F\u5217\u5316
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: false
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.0.103:3306/test
    password:
    username:
  #redis
  data:
    redis:
      database: 0
      host: 192.168.0.103
      password:
        #\u8BBE\u7F6E\u8FDE\u63A5\u6C60\u6700\u5927\u8FDE\u63A5\u6570
        #\u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4
        #\u8FDE\u63A5\u6C60\u4E2D\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5
      #\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5
      lettuce:
        cluster:
          refresh:
            adaptive: true
            period: 2000
        pool:
          max-active: 8
          max-wait: -1ms
          min-idle: 0
          max-idle: 8
          enabled: true

#\u6574\u5408mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  #\u6253\u5F00\u9A7C\u5CF0\u547D\u540D\u89C4\u5219
  configuration:
    map-underscore-to-camel-case: true