spring:
  application:
    name: authsvr
  profiles:
    active: dev
  config:
    import: nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  cloud:
    nacos:
      server-addr: 192.168.0.103:8848
      config:
        group: DEV_GROUP
        file-extension: yaml
server:
  port: 8081
